name: VOICE_MAIN_LOBBY
main: me.nathan.voice.MainLobbby
version: 1.0
description: >
             VOICE_MAIN_LOBBY
commands:
  f:
    description: Shoots fireworks!
  lobby:
    description: Sends you to the desired lobby!
  test:
    description: Sends you to the desired lobby!


